travis:
  secure:
    BINSTAR_TOKEN: EBvdGeucc2tXrEY0cA/v9y3b1hH82IUJxfijcbGyMAi8xGKp2SocmK0/HB1NebYt5hGVKbHtFl9ohgc9iJpP0YzzP/irUIBZ3VmFdZNpGueVU/0zUkKQLE396AlKL2OLowXelhB/4mDm3n340fTHrj9GkNB6etbrcYfv/Tz0gejEdbfijc2zFLF3rxPSd5lQQQeeh7jARb19z90IozahLOXo6bxLjRJoQnQcsDA7+OB33MvajOxXbicSLGmxJbZCKi2TEQjVKzvw7hJDcTTVPN34AlyUDvVJ3+aBhXl6RBGNssUwG7O7eKJ6I7BjOk0rGuitBxQAtSnpP3kui5u1LwS1cSakkvTC8SlFD38RbAy74RTWne5iNYBQq9sN1IFV5MYkL/sUowQqH02tigo5LVPLgJ1Is/SC5X4ybzSYuEDdVoFm9/kPJEjPa6Ss8S54AC08HwQXXuufY0VaTe0UfyOIhXMN+ALU+J3quEQhLZ/Jrg21B7YXmX4Fxn4gteN8PZpK91qNJvDMw1Sy+Yj63dzUCPk+L62gmWojPtYW/5Ufa6dHzKm9XHHMYwsUwRIER9naReNuJyVoXp0KhZkt2+cdHJBpmyqge1KEoKudJf3cbeu2TXE0JxbCJOObdeYZ+TfyTP/w1jDBBMBTvvtkTOrTctOht9t2ipozF19vJ6A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
